services:
  - type: web
    name: python-script-bot
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        value: "5740914918:AAG9JqEC3GssWFfZaLpT2Jjmv8dlC4KR6JI"
      - key: ADMINS
        value: "1813121392"
    plan: free
